/**
 * ExecutionRuntime — The runtime environment for one flowchart execution.
 *
 * Wires up the three memory primitives into a single container:
 *   - SharedMemory (the heap — shared state across all stages)
 *   - StageContext  (the call stack — per-stage execution tree)
 *   - EventLog      (the transaction log — commit history for replay)
 *
 * The engine (FlowchartTraverser) receives this as its runtime parameter.
 * After execution, consumers query it for the full execution state.
 */

import { EventLog } from '../memory/EventLog.js';
import type { RedactionRule } from '../memory/redaction.js';
import { SharedMemory } from '../memory/SharedMemory.js';
import { StageContext } from '../memory/StageContext.js';
import type {
  CommitBundle,
  CommitValuesMode,
  ReadTrackingMode,
  StageSnapshot,
  WriteProvenanceMode,
  WriteTrackingMode,
} from '../memory/types.js';
import { deepFreeze } from '../scope/protection/readonlyInput.js';
import type { ObserverStats } from './DeferredObserverTier.js';

/** Snapshot of a single recorder's collected data. */
/** The commit log's placeholder (`redactPatch`) — what the mirror's seed and patches both carry. */
const LOG_PLACEHOLDER = 'REDACTED';

export interface RecorderSnapshot {
  id: string;
  name: string;
  /** ScopeRecorder type and pattern description (e.g., "Translator (KeyedStore) — per-step token usage"). */
  description?: string;
  /** Preferred read-time operation — hints the UI about which view to show prominently. */
  preferredOperation?: 'translate' | 'accumulate' | 'aggregate';
  data: unknown;
  /**
   * Small machine-readable facts about the BUNDLE — how it was produced,
   * which projection of the recorder's data it is, what it deliberately
   * left out. Whatever the recorder's `toSnapshot()` put here, copied
   * through unchanged.
   *
   * The split with `description`: `description` is the sentence a human
   * reads; `meta` is what an offline consumer BRANCHES on. A recorder with
   * a "full" and a "lean" bundle shape that says so only in its
   * description forces every reader to string-match prose — and a reader
   * that doesn't renders an empty panel instead of saying "this recording
   * carries structure only".
   *
   * Not interpreted by the engine, so keys are the recorder's to choose;
   * keep the values JSON-safe, since this rides the snapshot out to disk.
   */
  meta?: Readonly<Record<string, unknown>>;
}

export type RuntimeSnapshot = {
  /**
   * The run this snapshot belongs to — the same `runId` stamped on every
   * `TraversalContext` (and thus every recorder event) of the run, so a
   * snapshot can be joined against an event stream or an external
   * correlation table. Read-only by contract: generated by the executor
   * (`runner/runId.ts`), never derived from snapshot contents.
   *
   * Lifecycle (matches the event model): fresh per `run()` AND per
   * `resume()` — resume is logically a distinct run, so a post-resume
   * snapshot carries a DIFFERENT runId than the paused run's snapshot.
   */
  readonly runId: string;
  sharedState: Record<string, unknown>;
  executionTree: StageSnapshot;
  /**
   * The commit log's fold BASE — the run's state before its first commit
   * (`initialContext` merged with `defaultValuesForContext`; on a resume, the
   * checkpoint's state). Deeply frozen and fully detached from the engine.
   *
   * Commit bundles are DIFFS, so the log alone cannot rebuild a value that
   * was seeded before the run and only ever merged afterwards. Shipping the
   * base WITH the log is what makes an offline fold — `stateAt(snapshot, i)`
   * from `footprintjs/trace` — reproduce the state a stage actually saw.
   *
   * OPTIONAL BY TYPE, and absent in exactly two cases. A plain `getSnapshot()`
   * always carries it, so a live fold reports `basis: 'initial+log'`. Under
   * `getSnapshot({ redact: true })` it is OMITTED — the base is the raw pre-run
   * seed and the redaction policy is not plumbed into the fold — so a fold of
   * a redacted snapshot degrades honestly to `basis: 'log-only'`. And it is
   * declared optional so that code written against 9.16.x — a test fixture or
   * a UI mock that CONSTRUCTS a `RuntimeSnapshot` literal — still compiles.
   * `stateAt` handles absence by saying so, never by folding a lie.
   */
  readonly initialState?: Record<string, unknown>;
  /**
   * The run's commit bundles, one per executed stage, in execution order —
   * a DETACHED, frozen copy of the engine's live log (a snapshot is a fold
   * result: it must not keep changing under the consumer that holds it).
   * The bundles inside are the engine's own objects, immutable after record.
   */
  commitLog: CommitBundle[];
  /**
   * Encoding discriminant for `commitLog` (#13c-B): `'full'` — every `set`
   * bundle stores the full final value (historical); `'delta'` — bundles may
   * carry `append`/`delete` trace verbs with verb-qualified `overwrite`
   * payloads (tails). Offline tooling keys on this field; a bundle stream
   * without context remains self-describing via the verbs themselves.
   */
  commitValues: CommitValuesMode;
  /** Per-write read-provenance dial (#P1) the run executed under — the
   *  offline-tooling discriminant for `TraceEntry.readKeys` availability. */
  writeProvenance: WriteProvenanceMode;
  /**
   * Per-subflow execution results, DUAL-KEYED (design: docs/design/subflow-commit-visibility.md):
   *   - by subflow PATH (`subflowId`, e.g. `'sf-pay'`) → the LAST iteration (back-compat); this
   *     is what `getSubtreeSnapshot(path)` and `listSubflowPaths()` resolve.
   *   - by per-execution mount `runtimeStageId` (e.g. `'sf-pay#5'`) → THAT iteration's result, so
   *     a LOOPING subflow retains EVERY iteration (not just the last). Look up a specific
   *     iteration as `subflowResults[node.runtimeStageId] ?? subflowResults[node.subflowId]`.
   * Both keys point at the same object for a single mount; iterate with care (count via the
   * path keys — those without `'#'`). The pause checkpoint carries only the path keys, lean.
   *
   * Under `getSnapshot({ redact: true })` each entry's `treeContext.globalContext` is that
   * subflow's OWN redacted mirror (9.20.0) — the fold of its scrubbed `history` — served as
   * one substituted object per mount (both keys still agree) — the wrapper is fresh per
   * `getSnapshot` call, the `globalContext` inside it is the stable mirror; plain, it is the subflow's
   * live heap. Without a policy there is no mirror and the two views are the same objects.
   */
  subflowResults?: Record<string, unknown>;
  /** Snapshot data from recorders that implement toSnapshot(). */
  recorders?: RecorderSnapshot[];
  /**
   * Deferred-observer accounting (RFC-001 Block 9) — queue depth, drops,
   * flush/budget counters, per-listener time attribution, and the
   * terminal-flush stranding count. ABSENT unless a recorder was attached
   * with `{ delivery: 'deferred' }` on this executor (zero-cost discipline).
   */
  observerStats?: ObserverStats;
};

export class ExecutionRuntime {
  public globalStore: SharedMemory;
  /**
   * Parallel redacted mirror of `globalStore`. Populated during traversal via
   * `StageContext.commit()` using the already-computed redacted patches.
   * Only exists when `enableRedactedMirror()` has been called — typically by
   * `FlowChartExecutor` when a `RedactionPolicy` is configured. Otherwise
   * undefined and zero cost.
   *
   * Read via `getSnapshot({ redact: true })`.
   */
  public redactedStore?: SharedMemory;
  public rootStageContext: StageContext;
  public executionHistory: EventLog;
  /** Original root for getSnapshot() — set before resume changes rootStageContext. */
  private _snapshotRoot?: StageContext;
  private _initialState: unknown;
  private _defaultValues: unknown;
  /** Active commit-values encoding (#13c-B) — surfaced as the snapshot
   *  discriminant {@link RuntimeSnapshot.commitValues}. */
  private commitValues: CommitValuesMode = 'full';

  /** Mirror of the writeProvenance dial for the snapshot discriminant (#P1). */
  private writeProvenance: WriteProvenanceMode = 'off';

  /** Memoized frozen fold base — see {@link RuntimeSnapshot.initialState}. */
  private _foldBase?: Record<string, unknown>;

  constructor(rootName: string, rootId: string, defaultValues?: unknown, initialState?: unknown) {
    this._initialState = initialState;
    this._defaultValues = defaultValues;
    this.globalStore = new SharedMemory(defaultValues, initialState);
    // The event log's fold base must be the SAME state the store starts from
    // — `initialContext` merged with `defaultValuesForContext`, which is what
    // `SharedMemory` computed above. Seeding the log from `initialState` alone
    // left `defaultValues` out of every replay, so a fold could not reproduce
    // the state a stage actually saw. `getState()` is the live context; the
    // EventLog constructor clones it, so the base stays detached.
    this.executionHistory = new EventLog(this.globalStore.getState());
    this.rootStageContext = new StageContext('', rootName, rootId, this.globalStore, '', this.executionHistory);
  }

  /**
   * Opt in to maintaining a parallel redacted mirror of `globalStore`. After
   * this call, every `StageContext.commit()` in the run writes the redacted
   * patches (the same ones fed to the event log) into `redactedStore` in
   * addition to the raw ones written to `globalStore`.
   *
   * The mirror is created lazily and propagated into all child / next
   * contexts, so it correctly reflects subflow-scope writes. When no
   * `RedactionPolicy` is configured, callers should skip this — unused
   * allocation, no functional difference in the snapshot.
   */
  enableRedactedMirror(): void {
    if (this.redactedStore) return; // idempotent
    // The mirror is a SERVED surface, so its seed must already be the
    // policy's view of the starting state: a policy key that arrives by
    // `initialContext` / `defaultValuesForContext` (or, on a cross-executor
    // resume, by the checkpoint's `sharedState`) and is never re-written
    // would otherwise sit in `getSnapshot({ redact: true })` in plaintext.
    // The rule must therefore be installed BEFORE this call — the executor
    // orders `useRedaction` first — and the seed is scrubbed with the LOG's
    // placeholder, the same string the redacted patches carry. Without a
    // rule (never the executor's case) the seed is the raw one.
    const rule = this.rootStageContext.getRedactionRule();
    this.redactedStore = new SharedMemory(
      rule ? rule.retainState(this._defaultValues, LOG_PLACEHOLDER) : this._defaultValues,
      rule ? rule.retainState(this._initialState, LOG_PLACEHOLDER) : this._initialState,
    );
    this.rootStageContext.useRedactedMirror(this.redactedStore);
  }

  /**
   * Install the run's redaction rule (the ONE owner of the verdict —
   * `memory/redaction.ts`) on the root stage context. Descendants inherit
   * via `createNext`/`createChild`; subflow roots inherit from their
   * parent-mount context via `SubflowExecutor`. Called by
   * `FlowChartExecutor.createTraverser()` on every run AND resume — after the
   * resume-path root swap, like the dials — so every staged write and tracked
   * read of the run, facade or not, is retained under the same policy.
   */
  useRedaction(rule: RedactionRule): void {
    this.rootStageContext.useRedactionRule(rule);
  }

  /**
   * Set the read-tracking policy (#14) on the root stage context. Descendant
   * contexts inherit via `createNext`/`createChild`; subflow root contexts
   * inherit from their parent-mount context via `SubflowExecutor`. Called by
   * `FlowChartExecutor.createTraverser()` when the executor's policy is not
   * the default `'full'` — including the resume path, where it is applied to
   * the freshly-created continuation root.
   */
  useReadTracking(mode: ReadTrackingMode): void {
    this.rootStageContext.useReadTracking(mode);
  }

  /**
   * Set the write-tracking policy (#13c-A) on the root stage context — the
   * sibling of {@link useReadTracking}, with identical plumbing: descendant
   * contexts inherit via `createNext`/`createChild`; subflow root contexts
   * inherit from their parent-mount context via `SubflowExecutor`. Called by
   * `FlowChartExecutor.createTraverser()` when the executor's policy is not
   * the default `'full'` — including the resume path, where it is applied to
   * the freshly-created continuation root.
   */
  useWriteTracking(mode: WriteTrackingMode): void {
    this.rootStageContext.useWriteTracking(mode);
  }

  /**
   * Set the commit-values encoding policy (#13c-B) on the root stage context
   * — the third dial of the {@link useReadTracking}/{@link useWriteTracking}
   * family, with identical plumbing: descendant contexts inherit via
   * `createNext`/`createChild`; subflow root contexts inherit from their
   * parent-mount context via `SubflowExecutor`. Called by
   * `FlowChartExecutor.createTraverser()` when the executor's policy is not
   * the default `'full'` — including the resume path, where it is applied to
   * the freshly-created continuation root.
   */
  useCommitValues(mode: CommitValuesMode): void {
    this.commitValues = mode;
    this.rootStageContext.useCommitValues(mode);
  }

  /**
   * Set the per-write read-provenance policy (#P1) on the root stage context
   * — the fourth dial of the family, identical plumbing: descendant contexts
   * inherit via `createNext`/`createChild`; subflow root contexts inherit
   * from their parent-mount context via `SubflowExecutor`. Called by
   * `FlowChartExecutor.createTraverser()` when the executor's policy is not
   * the default `'off'` — including the resume path.
   */
  useWriteProvenance(mode: WriteProvenanceMode): void {
    this.writeProvenance = mode;
    this.rootStageContext.useWriteProvenance(mode);
  }

  /** Preserve the current rootStageContext for snapshots before changing it for resume. */
  preserveSnapshotRoot(): void {
    if (!this._snapshotRoot) {
      this._snapshotRoot = this.rootStageContext;
    }
  }

  /**
   * The frozen, detached fold base served as {@link RuntimeSnapshot.initialState}.
   * Computed once (the base never changes after construction) and shared —
   * safe because it is deeply frozen, so no holder can mutate it or reach the
   * engine through it.
   */
  private getFoldBase(): Record<string, unknown> {
    if (!this._foldBase) {
      const base = this.executionHistory.getInitialState();
      this._foldBase = deepFreeze(base && typeof base === 'object' ? base : {}) as Record<string, unknown>;
    }
    return this._foldBase;
  }

  getPipelines(): string[] {
    const state = this.globalStore.getState();
    return state.pipelines ? Object.keys(state.pipelines as Record<string, unknown>) : [];
  }

  setRootObject(path: string[], key: string, value: unknown) {
    this.rootStageContext.setObject(path, key, value);
  }

  /**
   * Return the runtime snapshot.
   *
   * @param options.redact  When `true`, returns `sharedState` from the
   *   parallel redacted mirror (if one was enabled). This is the safe view
   *   for sharing traces externally — paste into a viewer, ship to support,
   *   etc. When the mirror was never enabled, falls back to raw `globalStore`
   *   and a dev-mode warning is emitted (silent in production).
   *
   *   Default `false` preserves the runtime view — necessary for pause /
   *   resume (resumption must replay against the real values, not
   *   '[REDACTED]').
   *
   * Other fields (`executionTree`, `commitLog`) are the same either way —
   * the commit log is already redacted at write-time, and the execution
   * tree only carries structural metadata.
   *
   * `initialState` (the fold base) is OMITTED under `redact: true`. It is the
   * run's raw pre-run seed — `initialContext` merged with
   * `defaultValuesForContext` — and it never passed through a redaction
   * policy: the policy scrubs WRITES at the scope facade, and the base was
   * never written by a stage. Serving it on the redacted surface would hand
   * back the original value of a seeded secret that a later commit had
   * scrubbed. A consumer folding without it gets `basis: 'log-only'` from
   * `stateAt`, which is the honest signal that the base did not travel with
   * this log — a partial answer that says it is partial, never a silent one.
   *
   * Returns `Omit<RuntimeSnapshot, 'runId'>`: the runtime is the memory
   * container and doesn't know which run it serves — `runId` is per-run
   * executor state, stamped by `FlowchartTraverser.getSnapshot()` (which
   * owns the run's id and already stamps it on every event). Subflows'
   * nested runtimes deliberately have NO runId of their own (a subflow is
   * part of the parent's logical run).
   */
  getSnapshot(options?: { redact?: boolean }): Omit<RuntimeSnapshot, 'runId'> {
    const snapshotRoot = this._snapshotRoot ?? this.rootStageContext;
    const useRedacted = options?.redact === true && this.redactedStore !== undefined;
    return {
      sharedState: useRedacted ? this.redactedStore!.getState() : this.globalStore.getState(),
      executionTree: snapshotRoot.getSnapshot(),
      // REDACTION: the fold base is the raw pre-run seed and no policy ever
      // touched it (policies scrub writes; nothing wrote the base). Omit it
      // rather than leak it — `stateAt` degrades to `basis: 'log-only'`.
      ...(useRedacted ? {} : { initialState: this.getFoldBase() }),
      // DETACHED: the engine keeps its live EventLog; the snapshot gets a
      // frozen copy of the array. Serving `list()` directly aliased the
      // internal array, so a snapshot taken mid-run kept growing under its
      // holder and a consumer could splice the engine's own history.
      commitLog: Object.freeze(this.executionHistory.list().slice()) as CommitBundle[],
      commitValues: this.commitValues,
      writeProvenance: this.writeProvenance,
    };
  }
}
