/**
 * ExecutionRuntime — The runtime environment for one flowchart execution.
 *
 * Wires up the three memory primitives into a single container:
 *   - SharedMemory (the heap — shared state across all stages)
 *   - StageContext  (the call stack — per-stage execution tree)
 *   - EventLog      (the transaction log — commit history for replay)
 *
 * The engine (FlowchartTraverser) receives this as its runtime parameter.
 * After execution, consumers query it for the full execution state.
 */

import type { CommitBundle, CommitValuesMode, LogAddress } from 'foottrace';
import type { WriteProvenanceMode } from 'foottrace/write';
import { EventLog, freezeRecord, LOG_PLACEHOLDER, SharedMemory } from 'foottrace/write';

import type { StageSnapshot } from '../memory/frameTypes.js';
import type { RunPolicy } from '../memory/runPolicy.js';
import { DEFAULT_RUN_POLICY } from '../memory/runPolicy.js';
import { StageContext } from '../memory/StageContext.js';
import type { ObserverStats } from './DeferredObserverTier.js';

/** Snapshot of a single recorder's collected data. */
export interface RecorderSnapshot {
  id: string;
  name: string;
  /** ScopeRecorder type and pattern description (e.g., "Translator (KeyedStore) — per-step token usage"). */
  description?: string;
  /** Preferred read-time operation — hints the UI about which view to show prominently. */
  preferredOperation?: 'translate' | 'accumulate' | 'aggregate';
  data: unknown;
  /**
   * Small machine-readable facts about the BUNDLE — how it was produced,
   * which projection of the recorder's data it is, what it deliberately
   * left out. Whatever the recorder's `toSnapshot()` put here, copied
   * through unchanged.
   *
   * The split with `description`: `description` is the sentence a human
   * reads; `meta` is what an offline consumer BRANCHES on. A recorder with
   * a "full" and a "lean" bundle shape that says so only in its
   * description forces every reader to string-match prose — and a reader
   * that doesn't renders an empty panel instead of saying "this recording
   * carries structure only".
   *
   * Not interpreted by the engine, so keys are the recorder's to choose;
   * keep the values JSON-safe, since this rides the snapshot out to disk.
   */
  meta?: Readonly<Record<string, unknown>>;
}

export type RuntimeSnapshot = {
  /**
   * The run this snapshot belongs to — the same `runId` stamped on every
   * `TraversalContext` (and thus every recorder event) of the run, so a
   * snapshot can be joined against an event stream or an external
   * correlation table. Read-only by contract: generated by the executor
   * (`runner/runId.ts`), never derived from snapshot contents.
   *
   * Lifecycle (matches the event model): fresh per `run()` AND per
   * `resume()` — resume is logically a distinct run, so a post-resume
   * snapshot carries a DIFFERENT runId than the paused run's snapshot.
   */
  readonly runId: string;
  sharedState: Record<string, unknown>;
  executionTree: StageSnapshot;
  /**
   * The commit log's fold BASE — the run's state before its first commit
   * (`initialContext` merged with `defaultValuesForContext`; on a resume, the
   * checkpoint's state). Deeply frozen and fully detached from the engine.
   *
   * Commit bundles are DIFFS, so the log alone cannot rebuild a value that
   * was seeded before the run and only ever merged afterwards. Shipping the
   * base WITH the log is what makes an offline fold — `stateAt(snapshot, i)`
   * from `foottrace` — reproduce the state a stage actually saw.
   *
   * OPTIONAL BY TYPE, and absent in exactly two cases. A plain `getSnapshot()`
   * always carries it, so a live fold reports `basis: 'initial+log'`. Under
   * `getSnapshot({ redact: true })` it is OMITTED — the base is the raw pre-run
   * seed and the redaction policy is not plumbed into the fold — so a fold of
   * a redacted snapshot degrades honestly to `basis: 'log-only'`. And it is
   * declared optional so that code written against 9.16.x — a test fixture or
   * a UI mock that CONSTRUCTS a `RuntimeSnapshot` literal — still compiles.
   * `stateAt` handles absence by saying so, never by folding a lie.
   */
  readonly initialState?: Record<string, unknown>;
  /**
   * The run's commit bundles, one per executed stage, in execution order —
   * a DETACHED, frozen copy of the engine's live log (a snapshot is a fold
   * result: it must not keep changing under the consumer that holds it).
   * The bundles inside are the engine's own objects, immutable after record.
   */
  commitLog: CommitBundle[];
  /** Identity of this log, stable across same-executor resume. Absent before binding or in older sources. */
  readonly logAddress?: LogAddress;
  /**
   * Encoding discriminant for `commitLog` (#13c-B): `'full'` — every `set`
   * bundle stores the full final value (historical); `'delta'` — bundles may
   * carry `append`/`delete` trace verbs with verb-qualified `overwrite`
   * payloads (tails). Offline tooling keys on this field; a bundle stream
   * without context remains self-describing via the verbs themselves.
   */
  commitValues: CommitValuesMode;
  /** Per-write read-provenance dial (#P1) the run executed under — the
   *  offline-tooling discriminant for `TraceEntry.readKeys` availability. */
  writeProvenance: WriteProvenanceMode;
  /**
   * Per-subflow execution results, DUAL-KEYED (design: docs/design/subflow-commit-visibility.md):
   *   - by subflow PATH (`subflowId`, e.g. `'sf-pay'`) → the LAST iteration (back-compat); this
   *     is what `getSubtreeSnapshot(path)` and `listSubflowPaths()` resolve.
   *   - by per-execution mount `runtimeStageId` (e.g. `'sf-pay#5'`) → THAT iteration's result, so
   *     a LOOPING subflow retains EVERY iteration (not just the last). Look up a specific
   *     iteration as `subflowResults[node.runtimeStageId] ?? subflowResults[node.subflowId]`.
   * Both keys point at the same object for a single mount; iterate with care (count via the
   * path keys — those without `'#'`). The pause checkpoint carries only the path keys, lean.
   *
   * Under `getSnapshot({ redact: true })` each entry's `treeContext.globalContext` is that
   * subflow's OWN redacted mirror (9.20.0) — the fold of its scrubbed `history` — served as
   * one substituted object per mount (both keys still agree) — the wrapper is fresh per
   * `getSnapshot` call, the `globalContext` inside it is the stable mirror; plain, it is the subflow's
   * live heap. Without a policy there is no mirror and the two views are the same objects.
   */
  subflowResults?: Record<string, unknown>;
  /** Snapshot data from recorders that implement toSnapshot(). */
  recorders?: RecorderSnapshot[];
  /**
   * Deferred-observer accounting (RFC-001 Block 9) — queue depth, drops,
   * flush/budget counters, per-listener time attribution, and the
   * terminal-flush stranding count. ABSENT unless a recorder was attached
   * with `{ delivery: 'deferred' }` on this executor (zero-cost discipline).
   */
  observerStats?: ObserverStats;
};

export class ExecutionRuntime {
  public globalStore: SharedMemory;
  /**
   * Parallel redacted mirror of `globalStore`. Populated by every commit that
   * staged a write (`memory/recordCommit.ts · recordCommit`), with the already-computed redacted patches.
   * Only exists when the run's policy keeps a mirror (`RunPolicy.mirror` —
   * `FlowChartExecutor` sets it when a `RedactionPolicy` is configured).
   * Otherwise undefined and zero cost.
   *
   * Read via `getSnapshot({ redact: true })`.
   */
  public redactedStore?: SharedMemory;
  public rootStageContext: StageContext;
  public executionHistory: EventLog;
  /** Original root for getSnapshot() — set before resume changes rootStageContext. */
  private _snapshotRoot?: StageContext;
  private _initialState: unknown;
  private _defaultValues: unknown;
  /** The run's policy (`memory/runPolicy.ts`) — installed on the root frame;
   *  its `commitValues` and `writeProvenance` are the snapshot discriminants. */
  private policy: RunPolicy;

  /** Memoized frozen fold base — see {@link RuntimeSnapshot.initialState}. */
  private _foldBase?: Record<string, unknown>;

  /**
   * @param policy The run's policy (`runPolicy.ts`, F5) — the four dials, the
   *   redaction rule, the mirror flag. Installed on the root frame here, so
   *   the FIRST commit (a subflow's seed, `history[0]`) already runs under it;
   *   every frame after inherits the same reference. Default: every dial at
   *   its default, no rule, no mirror.
   */
  constructor(
    rootName: string,
    rootId: string,
    defaultValues?: unknown,
    initialState?: unknown,
    policy: RunPolicy = DEFAULT_RUN_POLICY,
  ) {
    this._initialState = initialState;
    this._defaultValues = defaultValues;
    this.globalStore = new SharedMemory(defaultValues, initialState);
    // The event log's fold base must be the SAME state the store starts from
    // — `initialContext` merged with `defaultValuesForContext`, which is what
    // `SharedMemory` computed above. Seeding the log from `initialState` alone
    // left `defaultValues` out of every replay, so a fold could not reproduce
    // the state a stage actually saw. `getState()` is the live context; the
    // EventLog constructor clones it, so the base stays detached.
    this.executionHistory = new EventLog(this.globalStore.getState());
    this.policy = policy;
    this.rootStageContext = this.newRoot(rootName, rootId);
  }

  /**
   * A fresh root frame for this runtime — `globalStore`, `executionHistory`,
   * the run's policy and (when kept) the mirror. Also how `SubflowExecutor`
   * replaces a subflow's seed frame with the frame its first stage runs on.
   */
  newRoot(name: string, id: string): StageContext {
    const root = new StageContext('', name, id, this.globalStore, '', this.executionHistory);
    this.installPolicy(root);
    return root;
  }

  /**
   * Install the run's policy on the CURRENT root frame — a same-executor
   * resume, whose continuation root (`leaf.createNext`) is advanced before
   * the executor builds this leg's policy (a fresh rule per leg). Every
   * descendant takes the reference from there.
   */
  usePolicy(policy: RunPolicy): void {
    this.policy = policy;
    this.installPolicy(this.rootStageContext);
  }

  /**
   * The policy on `root`, and the mirror store when the policy keeps one.
   * The mirror is a SERVED surface, so its seed must already be the policy's
   * view of the starting state: a policy key that arrives by `initialContext`
   * / `defaultValuesForContext` (or, on a cross-executor resume, by the
   * checkpoint's `sharedState`) and is never re-written would otherwise sit
   * in `getSnapshot({ redact: true })` in plaintext — so the seed is scrubbed
   * with the LOG's placeholder, the same string the redacted patches carry.
   * Created once per runtime (a subflow's runtime keeps its own; its seed is
   * empty — the input arrives as a commit).
   */
  private installPolicy(root: StageContext): void {
    root.usePolicy(this.policy);
    if (!this.policy.mirror) return;
    if (!this.redactedStore) {
      const rule = this.policy.redaction;
      this.redactedStore = new SharedMemory(
        rule ? rule.retainState(this._defaultValues, LOG_PLACEHOLDER) : this._defaultValues,
        rule ? rule.retainState(this._initialState, LOG_PLACEHOLDER) : this._initialState,
      );
    }
    root.useRedactedMirror(this.redactedStore);
  }

  /** Preserve the current rootStageContext for snapshots before changing it for resume. */
  preserveSnapshotRoot(): void {
    if (!this._snapshotRoot) {
      this._snapshotRoot = this.rootStageContext;
    }
  }

  /**
   * The frozen, detached fold base served as {@link RuntimeSnapshot.initialState}.
   * Computed once (the base never changes after construction) and shared —
   * safe because it is deeply frozen, so no holder can mutate it or reach the
   * engine through it; a base holding a Date, Map, buffer … (what freezing
   * cannot seal) is served by the public snapshot as a copy of its open paths
   * (`runner/snapshot.ts · servedSnapshot`, `capture/freeze.ts · serveRecord`,
   * 9.44.2).
   */
  private getFoldBase(): Record<string, unknown> {
    if (!this._foldBase) {
      const base = this.executionHistory.getInitialState();
      this._foldBase = freezeRecord(base && typeof base === 'object' ? base : {}) as Record<string, unknown>;
    }
    return this._foldBase;
  }

  getPipelines(): string[] {
    const state = this.globalStore.getState();
    return state.pipelines ? Object.keys(state.pipelines as Record<string, unknown>) : [];
  }

  setRootObject(path: string[], key: string, value: unknown) {
    this.rootStageContext.setObject(path, key, value);
  }

  /**
   * Return the runtime snapshot.
   *
   * @param options.redact  When `true`, returns `sharedState` from the
   *   parallel redacted mirror (if one was enabled). This is the safe view
   *   for sharing traces externally — paste into a viewer, ship to support,
   *   etc. When the mirror was never enabled, falls back to raw `globalStore`
   *   and a dev-mode warning is emitted (silent in production).
   *
   *   Default `false` preserves the runtime view — necessary for pause /
   *   resume (resumption must replay against the real values, not
   *   '[REDACTED]').
   *
   * Other fields (`executionTree`, `commitLog`) are the same either way —
   * the commit log is already redacted at write-time, and the execution
   * tree only carries structural metadata.
   *
   * `initialState` (the fold base) is OMITTED under `redact: true`. It is the
   * run's raw pre-run seed — `initialContext` merged with
   * `defaultValuesForContext` — and it never passed through a redaction
   * policy: the policy scrubs WRITES at the scope facade, and the base was
   * never written by a stage. Serving it on the redacted surface would hand
   * back the original value of a seeded secret that a later commit had
   * scrubbed. A consumer folding without it gets `basis: 'log-only'` from
   * `stateAt`, which is the honest signal that the base did not travel with
   * this log — a partial answer that says it is partial, never a silent one.
   *
   * Returns `Omit<RuntimeSnapshot, 'runId'>`: the runtime is the memory
   * container and doesn't know which run it serves — `runId` is per-run
   * executor state, stamped by `FlowchartTraverser.getSnapshot()` (which
   * owns the run's id and already stamps it on every event). Subflows'
   * nested runtimes deliberately have NO runId of their own (a subflow is
   * part of the parent's logical run).
   */
  getSnapshot(options?: { redact?: boolean }): Omit<RuntimeSnapshot, 'runId'> {
    const snapshotRoot = this._snapshotRoot ?? this.rootStageContext;
    const useRedacted = options?.redact === true && this.redactedStore !== undefined;
    return {
      sharedState: useRedacted ? this.redactedStore!.getState() : this.globalStore.getState(),
      executionTree: snapshotRoot.getSnapshot(),
      // REDACTION: the fold base is the raw pre-run seed and no policy ever
      // touched it (policies scrub writes; nothing wrote the base). Omit it
      // rather than leak it — `stateAt` degrades to `basis: 'log-only'`.
      ...(useRedacted ? {} : { initialState: this.getFoldBase() }),
      // DETACHED: the engine keeps its live EventLog; the snapshot gets a
      // frozen array of its own (`recorded()` builds a new one). Serving the
      // internal array aliased it, so a snapshot taken mid-run kept growing
      // under its holder and a consumer could splice the engine's own history.
      // The bundles in it are the log's own, frozen at `EventLog · record`
      // (F3). The public snapshot serves them (`runner/snapshot.ts ·
      // servedSnapshot`, 9.44.2); this one is also the engine's own — a
      // subflow mount takes it once per mount — so the run path serves nothing.
      commitLog: Object.freeze(this.executionHistory.recorded()) as CommitBundle[],
      ...(this.executionHistory.address === undefined ? {} : { logAddress: this.executionHistory.address }),
      commitValues: this.policy.commitValues,
      writeProvenance: this.policy.writeProvenance,
    };
  }
}
